version: 1

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logs/kedro.log
    maxBytes: 10485760  # 10MB
    backupCount: 3

root:
  level: INFO
  handlers: [console, file]

loggers:
  kedro:
    level: INFO
    handlers: [console, file]
    propagate: false

  account_tax:
    level: DEBUG
    handlers: [console, file]
    propagate: false
