# Split and Train pipeline parameters

split:
  label_column: acct_code
  seed: 42
  test_size: 0.2
  val_size: 0.1
  max_classes: 1000
  dummy_prefix: dummy
  dummy_label: dummy1
  labelize_num_proc: 4

train:
  serialization:
    text_columns: []
    separator: ", "
    include_column_names: true
    num_proc: 4
    retain_columns:
      - text
      - labels
      - acct_code
    label_column: acct_code
  tokenization:
    model_name: "Qwen/Qwen2.5-0.5B"
    max_length: 512
    truncation: true
    num_proc: 4
    diagnostics:
      sample_size: 5
      percentiles: [50, 75, 90, 95, 99]
      seed: 42
