# Training pipeline parameters

# ----------------------------------------------------------------------------
# Split configuration (shared with split pipeline)
# ----------------------------------------------------------------------------
split:
  label_column: acct_code
  seed: 42
  test_size: 0.2
  val_size: 0.1
  max_classes: 280
  labelize_num_proc: 8
  extract_ratio: 0.1
  extract_seed: 42
  stratify_extract: true

# ----------------------------------------------------------------------------
# Tokenization, model, and training configuration
# ----------------------------------------------------------------------------
train:
  serialization:
    text_columns: []
    separator: "| "
    key_value_separator: ":"
    include_column_names: true
    num_proc: 8

  tokenization:
    model_name: "Qwen/Qwen3-4B"
    max_length: 256
    truncation: true
    padding: "longest"
    num_proc: 8
    sample_size: 10
    output_dir: "data/06_models/tokenized_datasets"

  # Default LoRA configuration (anchored for reuse)
  lora_defaults: &lora_cfg
    task_type: "SEQ_CLS"
    r: 128
    lora_alpha: 256
    lora_dropout: 0.05
    target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
    layers_to_transform: [28, 29, 30, 31, 32, 33, 34, 35]
    modules_to_save: ["score"]
    bias: "lora_only"

  data:
    train_split: "train"
    eval_split: "valid"
    test_split: "test"

  model:
    name_or_path: "Qwen/Qwen3-4B"
    num_labels: null
    torch_dtype: "bfloat16"
    trust_remote_code: true
    gradient_checkpointing: false

  training_args:
    output_dir: "data/06_models/checkpoints"
    num_train_epochs: 3
    per_device_train_batch_size: 32
    per_device_eval_batch_size: 32
    gradient_accumulation_steps: 1
    learning_rate: 1.0e-5
    weight_decay: 0.002
    warmup_ratio: 0.01
    lr_scheduler_type: "cosine"
    eval_strategy: "steps"
    eval_steps: 1000
    save_strategy: "steps"
    save_steps: 5000
    save_total_limit: 3
    logging_steps: 10
    report_to: ["mlflow"]
    bf16: true
    fp16: false
    gradient_checkpointing: false
    dataloader_num_workers: 8
    seed: 42
    load_best_model_at_end: true
    metric_for_best_model: "accuracy"
    greater_is_better: true

  lora:
    enable: true
    config:
      <<: *lora_cfg

  deepspeed:
    num_gpus: 4
    config:
      train_micro_batch_size_per_gpu: 32
      gradient_accumulation_steps: 1
      zero_optimization:
        stage: 2
        offload_param:
          device: "none"
          pin_memory: true
        offload_optimizer:
          device: "cpu"
          pin_memory: true
        allgather_bucket_size: 5e8
        reduce_bucket_size: 5e8
      gradient_clipping: 1.0
      bf16:
        enabled: true
      fp16:
        enabled: false

  training_script:
    path: "src/train/main_yaml.py"
    config_output_path: "data/06_models/run_config/train_config.yml"

  metrics:
    path: "data/06_models/metrics/train_metrics.json"
